apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: guestbook-simple-dev
images:
- name: ghcr.io/Vamsi-344/guestbook
  newTag: v0.0.1
- name: ghcr.io/vamsi-344/guestbook
  newTag: v0.0.2
